### PR TITLE
Add major mode doc

### PR DESCRIPTION
**Pull request by stevenguh**
This PR add the major mode doc for https://github.com/VSpaceCode/VSpaceCode/pull/111

@MarcoIeni Should we have a develop branch on this repo to stage the unreleased feature?

### CODE REVIEW

**Comment by marcoieni** [comment]
I tried to improve the description a little bit, let me know what you think.

> Should we have a develop branch on this repo to stage the unreleased feature?

I haven't figured out this aspect yet.
For this specific pull request, we could merge it once the new VSpaceCode is out, but we should evaluate a different solution for sure.
I will open an issue about this.

**Comment by stevenguh** [comment]
> I tried to improve the description a little bit, let me know what you think.

It sounds better and provides more information :) Thanks for revising it.

> For this specific pull request, we could merge it once the new VSpaceCode is out, but we should evaluate a different solution for sure.

Sounds good to me. We probably ship a new version with the new major mode soon?

> I will open an issue about this.

Awesome! thanks.

**Comment by marcoieni** [comment]
I opened #8 

Regarding this PR.. I don't thing that a table is the right format to list the major modes, because major modes might require more than one extension. Comma separated values in a table is not the best maybe, because the length of a cell could grow a lot.

Maybe something like this:

```
## Markdown

Required exetensions:
- [Markdown All in One](https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one)
```

**Comment by stevenguh** [comment]
> I opened #8

awesome!! Thanks

---

Your format makes sense to me. Plus, we can have more space to put more description per major mode if needed.

**Comment by marcoieni** [comment]
Ok, I will edit it tomorrow if I can

**Comment by marcoieni** [comment]
Done. In my opinion when the new version of VSpaceCode is released, this can be merged.

**Comment by stevenguh** [comment]
Released and merge. Make sense. We should keep staging in the pull request until #8 is fixed.

**Pull request merged**
