### PR TITLE
Java major mode

### PR DESCRIPTION
**Pull request by erichonorez**
Hello,

This is an update of the documentation for the java major mode (see this [PR](https://github.com/VSpaceCode/VSpaceCode/pull/301)).

### CODE REVIEW

**Comment by erichonorez** [comment]
I see that my PR include 3 other commits [713798e](https://github.com/VSpaceCode/vspacecode.github.io/pull/63/commits/713798e9315cbb8897e1c70f3711cba818759439), [6cadffc](https://github.com/VSpaceCode/vspacecode.github.io/pull/63/commits/6cadffc41bfee435d274d5e226718d87c6642ee4), [5ee1659](https://github.com/VSpaceCode/vspacecode.github.io/pull/63/commits/5ee1659e642f229b5293ec3eb718ea3c2900001f). 

I created my branch `java-major-mode` from `master` and then created this PR in `vspacecode-next`. Should I create my branch from `spacecode-next` ?

**Comment by marcoieni** [comment]
The PR was closed automatically because of a GH setting. I removed that setting now.

Since we forgot to merge the `vspacecode-next` branch into master, you are seeing more commits. 
Can you try to open the PR again, from the `vspacecode-next` branch, as you said?

**Comment by erichonorez** [comment]
> The PR was closed automatically because of a GH setting. I removed that setting now.
> 
> Since we forgot to merge the `vspacecode-next` branch into master, you are seeing more commits. Can you try to open the PR again, from the `vspacecode-next` branch, as you said?

I'm not sure of what I have to do. I see that you reopened this PR yesterday and you merged `vspacecode-next` into `java-major-mode`. 

Do you still want me to create a new PR with a branch that starts from `spacecode-next` ?

**Comment by stevenguh** [comment]
The commit history was a bit weird and having some duplicated commits from the past for some reason. I took the liberty to rebase this so the file changes are correct now. Thanks for contributing btw.

**Review by marcoieni — APPROVED** [review]

**Pull request merged**
